title: "&f[&a小游戏&f]"

scoreboard-title: "&a小游戏"

command-player: "gd"

command-admin: "gda"

command-msg: "gds"



# 是否保存玩家背包
save-playerInventory:  true

# 递增经验
# 每下一级的经验为 up-exp * 等级
up-exp: 500


game-logo: "author: sobadfish "

join-menu:
  "Room#1":
    buttonImg:
      type: "path"
      path: "textures/ui/icon_recipe_item"
    rooms:
      - "游戏房间"